services:
    app:
        container_name: tech-talk
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tech-net
        extra_hosts:
            - "host.docker.internal:host-gateway"

    nginx:
        container_name: tech-talk-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - tech-net

networks:
    tech-net:
        driver: bridge
